services:
  - type: web
    name: schoolmart-backend
    env: node
    rootDir: backend
    buildCommand: npm ci --include=dev && npm run build
    startCommand: npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 4000
      - key: DB_HOST
        fromDatabase:
          name: schoolmart-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: schoolmart-db
          property: port
      - key: DB_USERNAME
        fromDatabase:
          name: schoolmart-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: schoolmart-db
          property: password
      - key: DB_NAME
        fromDatabase:
          name: schoolmart-db
          property: database
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: 24h
      - key: EMAIL_HOST
        value: smtp.gmail.com
      - key: EMAIL_PORT
        value: 587
      - key: EMAIL_SECURE
        value: false
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: CLOUDINARY_FOLDER
        value: schoolmart
      - key: TWILIO_ACCOUNT_SID
        sync: false
      - key: TWILIO_AUTH_TOKEN
        sync: false
      - key: TWILIO_PHONE_NUMBER
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: GOOGLE_REDIRECT_URI
        sync: false
      - key: FACEBOOK_APP_ID
        sync: false
      - key: FACEBOOK_APP_SECRET
        sync: false
      - key: FACEBOOK_REDIRECT_URI
        sync: false
    healthCheckPath: /health
    plan: free

databases:
  - name: schoolmart-db
    databaseName: schoolmart
    user: schoolmart
    plan: free
    region: oregon